N_NEURONS = 500

N_A = 200
N_B = 300

VOCAB_STRING = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,!?;:()[]{}'\"-_\n"
VOCAB_SIZE = len(VOCAB_STRING)
CHAR_TO_IDX = {c: i for i, c in enumerate(VOCAB_STRING)}
IDX_TO_CHAR = {i: c for i, c in enumerate(VOCAB_STRING)}

MAX_DELAY = 4
SPARSITY = 0.12
EXC_RATIO = 0.80
INH_RATIO = 0.20

SENSORY_NODES = list(range(VOCAB_SIZE))

LEAK_RATE_A = 0.8
SPECTRAL_RADIUS_A = 0.70

LEAK_RATE_B = 0.05
SPECTRAL_RADIUS_B = 0.98

A_TO_B_SPARSITY = 0.06
B_TO_A_SPARSITY = 0.04
A_TO_B_SCALE = 0.1
B_TO_A_SCALE = 0.002

SENSORY_GAIN = 0.4
NOISE_STD = 0.01

STEPS_PER_TOKEN = 15
WASHOUT_STEPS = 10

RIDGE_ALPHA = 0.01
TEMPERATURE = 0.15

DEFAULT_SEED = 42
