import torch

LAMBDA_CUTOFF = 10.0
M_REGULATOR = 1.0

SIMPLICIAL_DIM = 256
VOCAB_SIZE = 100278

N_USF_LAYERS = 6
USF_N_HEADS = 8
USF_HEAD_DIM = 64
USF_FFN_DIM = 1024
RETRO_WINDOW = 16
USF_MAX_SEQ_LEN = 512

SIGMA2_USF_LIK = 1.0
SIGMA2_USF_PRIOR = 0.1
USF_LEARNING_RATE = 1e-4
USF_SZILARD_REJECT = True

USF_NEGENTROPY_WINDOW = 100
RETRO_LOSS_SCALE = 0.1
SENSOR_LOSS_SCALE = 1.0
LM_LOSS_SCALE = 1.0

USF_DTYPE = torch.float32
USF_DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

USF_MODEL_PATH = '/tmp/usf_checkpoint.pt'
USF_TOKENIZER_PATH = '/tmp/erebus_memory/usf_tokenizer'
USF_TEMPERATURE = 0.8
USF_MAX_GEN_TOKENS = 128
USF_OLLAMA_REFINEMENT = True
USF_CONTEXT_TOKENS = 256
USF_TRAIN_EVERY_N_STEPS = 0
USF_LEARNING_MODE = 'offline'
